version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  install:
    desc: Install dependencies
    cmds:
      - corepack enable
      - pnpm install

  build:
    desc: Build
    cmds:
      - pnpm run build

  test:
    desc: Unit tests
    cmds:
      - pnpm run test

  version-up:
    desc: |
      Build
          ∟ [Ex] task version-up VERSION=1.2.3
    deps:
      - build
      - test
    cmds:
      - git fetch --all
      - git checkout master
      - git pull
      - pnpm version {{.VERSION}}
      - git push
      - git push --tags
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."

  release:
    desc: Packaging and uploading to pnpm
    cmds:
      - task: install
      - task: build
      - task: test
      - pnpm publish
    preconditions:
      - sh: "[ -z {{.VERSION}} ]"
        msg: "An unnecessary argument, VERSION is specified. Did you mean 'task version-up'?"
