name: "Release"
on: workflow_dispatch
permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Build"
        run: |
          npm i -g pnpm@11.0.8
          pnpm install
          pnpm pre:push
          pnpm build
      - name: "Prepare release"
        run: pnpm add -D conventional-changelog-conventionalcommits
      - name: "Release"
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 24.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
